---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Lint

"on":
  push:
    branches:
      - "*"
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: psf/black@main

  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jgoguen/gh-actions/shellcheck@main

  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yamllint
        uses: jgoguen/gh-actions/yaml-lint@main
        with:
          source: ./.github/workflows/
