---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Populate Release

"on":
  push:
    tags:
      - "v*"

jobs:
  upload-assets:
    runs-on: "ubuntu-latest"

    steps:
      - name: Install repo dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Check out release tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch calibre
        run: ./scripts/update-calibre.py

      - name: Build ZIP files
        run: ./scripts/build.sh build

      - name: Create GitHub release
        if: runner.environment == 'github-hosted'
        uses: https://github.com/softprops/action-gh-release@v2
        with:
          files: "release/*.zip"
          make_latest: true
          generate_release_notes: true

      - name: Create Forgejo release
        if: runner.environment != 'github-hosted'
        uses: https://code.forgejo.org/actions/forgejo-release@v2
        with:
          direction: upload
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref_name }}
          release-dir: release
          release-notes-assistant: true
