---
# vim: fileencoding=UTF-8:expandtab:autoindent:ts=2:sts=2:sw=2:filetype=yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Populate Release

"on":
  push:
    tags:
      - "v*"

jobs:
  upload-assets:
    runs-on: "ubuntu-latest"

    steps:
      - name: Install repo dependencies
        run: sudo apt install -y gettext

      - name: Check out release tag
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch calibre
        run: ./scripts/update-calibre.py

      - name: Build ZIP files
        run: ./scripts/build.sh build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          make_latest: true
